// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CSGfTLYfdmtWf-RbXilmdwArEf3u6Co',
    appId: '1:129268242627:web:b793fa87b527ce6a496a76',
    messagingSenderId: '129268242627',
    projectId: 'fir-95d8f',
    authDomain: 'fir-95d8f.firebaseapp.com',
    storageBucket: 'fir-95d8f.appspot.com',
    measurementId: 'G-27NLD2RF8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOU8y1iCEaadEmga1NxbWVdXKOwY7V0SY',
    appId: '1:129268242627:android:794963761825e463496a76',
    messagingSenderId: '129268242627',
    projectId: 'fir-95d8f',
    storageBucket: 'fir-95d8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_H-JneCTAJ5M7MHoOD_75c9IoHXHjmc0',
    appId: '1:129268242627:ios:01b2cb057e9704ab496a76',
    messagingSenderId: '129268242627',
    projectId: 'fir-95d8f',
    storageBucket: 'fir-95d8f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_H-JneCTAJ5M7MHoOD_75c9IoHXHjmc0',
    appId: '1:129268242627:ios:01b2cb057e9704ab496a76',
    messagingSenderId: '129268242627',
    projectId: 'fir-95d8f',
    storageBucket: 'fir-95d8f.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6CSGfTLYfdmtWf-RbXilmdwArEf3u6Co',
    appId: '1:129268242627:web:6c1dff2e36dc2266496a76',
    messagingSenderId: '129268242627',
    projectId: 'fir-95d8f',
    authDomain: 'fir-95d8f.firebaseapp.com',
    storageBucket: 'fir-95d8f.appspot.com',
    measurementId: 'G-SE91N1NP49',
  );
}
